# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование товара')),
                ('item_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_receipt_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время поступления')),
                ('item_capture', models.ImageField(blank=True, null=True, upload_to='item/%Y/%m/%d')),
                ('item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'ordering': ['item_name', 'item_receipt_date'],
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('item_name', 'item_description', 'item_receipt_date')]),
        ),
    ]
