# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(db_index=True, max_length=50)),
                ('category_discription', models.TextField(blank=True)),
                ('category_capture', models.ImageField(upload_to='category/')),
            ],
            options={
                'ordering': ['category_title'],
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('category_title', 'category_discription', 'category_capture')]),
        ),
    ]
